---
title: "Visualization I"
output: github_document
author: Shunyi Zhang
editor_options: 
  chunk_output_type: console
---

```{r setup}
library(tidyverse)
library(ggridges)
```

## Load the Weather Data

```{r tidy data}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"),
    date_min = "2017-01-01",
    date_max = "2017-12-31"
  ) %>% 
  mutate(
    name = recode(
      id,
      USW00094728 = "CentralPark_NY",
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"
    ),
    tmin = tmin / 10,
    tmax = tmax / 10
  ) %>% 
  select(name, id, everything())

head(weather_df)
```


## Basic Scatterplots

Create forst scatterplot.

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```

Another approach. (fit overall syntax)

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

Save and edit a plot object. (least frequently)

```{r}
weather_plot = 
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax))

weather_plot + geom_point()
```

